name: Alex Azevedo
description: Theo's fater, software engineer, passionate entrepreneur, drones lover
meta_description: "Theo's father, software engineer, internet enthusiast, passionate entrepreneur, drones and paragliding lover"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.alexazevedo.com.br'
google_analytics: 'UA-71672530-1'

# Details for the RSS feed generator
url:            'http://www.alexazevedo.com.br'
author:         'Alex Azevedo'
